### ISSUE TITLE
Duplicate spheRlab_tarballs repository

### ISSUE THREAD

**Issue by koldunovn** [helgegoessling/spheRlab#2]
There is  [repository with tarbals](https://github.com/helgegoessling/spheRlab_tarballs) associated with this project. It's not that necessary since there is mechanism of [releases](https://github.com/helgegoessling/spheRlab/releases) for the stable version of code that you would like to distribute. If someone would like to have development version of the code, they can download it by pressing the "Clone or download" button at the main page of the repository.

**Comment by koldunovn** [comment]
call for @helgegoessling

**Comment by helgegoessling** [comment]
I will retain the extra tarball repository for the time being because these 'built' tarballs of tagged versions make it unnecessary for package users to run 'R CMD build'. I believe R users (non-developers, including on Windows ;-)) are used to just installing a ready-to-use package.
