### ISSUE TITLE
regridding workflow missing

### ISSUE THREAD

**Issue by chrisdane** [helgegoessling/spheRlab#5]
Hi

Could you please describe the workflow to regrid unstructured fesom1 data that has not the necessary grid variables? Without the grid variables, the usual cdo genycon and remap commands do not work.

For testing you can use e.g. `/work/ba0989/a270077/CMIP6_PMIP4/a270073/CMIP6/CMIP_PMIP/dynveg_true/PI-CTRL6/outdata/fesom/PI-CTRL6_fesom_zos_21040101.nc`

Thanks a lot!
Chris

**Comment by helgegoessling** [comment]
Hi Chris,

If a "grid description file" for the considered FESOM grid exists, which is the case for this one, you can remap directly with CDO as follows (for example):

> cdo remapycon,global_1 -setgrid,/pool/data/AWICM/FESOM1/MESHES/core/griddes.nc /work/ba0989/a270077/CMIP6_PMIP4/a270073/CMIP6/CMIP_PMIP/dynveg_true/PI-CTRL6/outdata/fesom/PI-CTRL6_fesom_zos_21040101.nc PI-CTRL6_fesom_zos_21040101_1deg.nc

In other cases where such a grid description file does not yet exist, one can create one by using the spheRlab functions sl.grid.readFESOM() and sl.grid.writeCDO(), see the function documentation for details. If you need to do that and encounter problems, please let me know!

Cheers,
Helge

**Comment by chrisdane** [comment]
Great thanks Helge!
