### ISSUE TITLE
sl.grid.FESOM3Ddata1Dto2D error data in aux3d.out is inconsistent with the number of depth levels

### ISSUE THREAD

**Issue by chrisdane** [helgegoessling/spheRlab#6]
Hi

Running
```r
spheRlab::sl.grid.FESOM3Ddata1Dto2D(
        ifile="/work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/historical2/outdata/fesom/thetao_fesom_20140101.nc", 
        ofile="~/levelwise.nc",
        meshdir="/pool/data/AWICM/FESOM1/MESHES/core",
        idepth="/pool/data/AWICM/FESOM1/MESHES/core/nod3d.out")
```
yields the error
```
Error in spheRlab::sl.grid.FESOM3Ddata1Dto2D(ifile = files[fi], ofile = ofile,  : 
  data in aux3d.out is inconsistent with the number of depth levels
```

Thanks a lot for help and cheers,
Chris

```r
packageVersion("spheRlab")
[1] ‘1.1.5’
rversion
platform       x86_64-conda-linux-gnu
version.string R version 4.1.0 (2021-05-18)
```

**Comment by chrisdane** [comment]
Ah, omitting the `idepth` argument helps.

**Comment by helgegoessling** [comment]
Good that you find how to make it work! Can the issue be closed?

**Comment by chrisdane** [comment]
If you want you can close it but I think the function does not work as intended (error if correct `idepth` arg is provided).

**Comment by helgegoessling** [comment]
OK, I'll look into it asap...

**Comment by helgegoessling** [comment]
@chrisdane , the argument description states: _idepth: a character specifying the name of an ascii file with the ocean level depths, from surface to bottom with one row for each depth value. If NULL, this information is retrieved from the file 'nod3d.out' in 'meshdir'._  ... meaning that, if the depth info is supposed to be derived from that nod3d.out file, then you should not pass it explicitly through this argument, but it's expected to be in the meshdir. Also, note that a typical nod3d.out file is not structured as described in the argument description. An ascii file as described is only needed if nod3d.out does not exist.
